import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"], display: 'swap' });

export const metadata = {
  title: "WalletWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
      <body className={`${inter.className}`}>
        <ClerkProvider>

        {/* header component can be added here if needed */}
        <Header />

        <main className = "min-h-screen">{children}</main>

        {/* footer component */}
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>&copy; {new Date().getFullYear()} Finance Manager. All rights reserved.</p>
          </div>
        </footer>
        </ClerkProvider>
      </body>
    </html>
    
    
  );
}
